version: '3.4'

services:
  reportservice.api:
    image: ${DOCKER_REGISTRY-}reportserviceapi
    build:
      context: .
      dockerfile: ReportService.API/Dockerfile
    restart: on-failure
    depends_on:
      rabbit:
        condition: service_healthy

  contactservice.api:
    image: ${DOCKER_REGISTRY-}contactserviceapi
    build:
      context: .
      dockerfile: ContactService.API/Dockerfile
    restart: on-failure
    depends_on:
      rabbit:
        condition: service_healthy

  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "rabbit", "5672" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - RABBITMQ_DEFAULT_VHOST=CUSTOM_HOST
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest